# ---------------------------------------------------------------- #
#               Общий каркас страниц админки (autoinclude)         #
# ---------------------------------------------------------------- #
[admin:autoinclude:footer]
head = "Free disk space: %s"
text = "<strong> %s </strong> - Admin panel. Copyright %s"
