# ---------------------------------------------------------------- #
#                          Редактор кода                           #
# ---------------------------------------------------------------- #
[admin:codeeditor:title]
head = "Code editor"
[admin:codeeditor:blocks]
code.head = "Code"
code.info = 'click "Save" to apply changes'
config.head = "Configuration"
config.info = 'click "Save" to apply changes'
save.head = "Save"
tree.head = "File tree"
tree.info = "use it to open a file for editing"
info.head = "Info"
[admin:codeeditor:js]
ok = "Done"
neterr = "A network error occurred while sending the form! Please try again"
[admin:codeeditor:saved]
text = "Saved successfully"
[admin:codeeditor:savefail]
text = "Failed to save the file"
