# ---------------------------------------------------------------- #
#                       Модули и провайдеры                        #
# ---------------------------------------------------------------- #
[admin:components:packages]
head = "Installed composer packages"
[admin:components:packages:block]
head = "Installed packages"
info = "Install additional packages via <b> composer </b> into the <b> %s </b> directory or add them there manually"
[admin:components:packages:filters]
all = "All"
composer = "Composer"
[admin:components:packages:cols]
package = "Package"
vendor = "Vendor"
desc = "Description"
type = "Type"
added = "Added"
action = "Action"
# ---------------------------------------------------------------- #
#                           Юниты и провайдеры                     #
# ---------------------------------------------------------------- #
[admin:components:units]
head = "System modules"
[admin:components:units:analize]
head = "Analyze modules"
[admin:components:providers]
head = "Data providers"
[admin:components:providers:analize]
head = "Analyze providers"
[admin:components:units:head]
head = "Platform components"
create = "Create new module"
[admin:components:units:search]
placeholder = "Search"
[admin:components:units:cols]
updated = "Updated:"
size.title = "File size"
time.title = "Initialization time"
config = "Configuration"
code = "View code"
[admin:components:units:modal]
head = "Module errors"
info = "This window shows the errors that occurred while initializing the module"
close = "Close"
srclose = "Close"
[admin:components:units:status]
idle = "Not analyzed"
ready = "Ready"
init = "Initialization"
syntax = "Syntax"
[admin:components:units:suffix]
kb = " KB"
sec = " sec"
[admin:components:units:js]
checking = " Checking..."
refresh = " Refresh"
# ---------------------------------------------------------------- #
#                     Контроллеры приложения                       #
# ---------------------------------------------------------------- #
[admin:components:controllers]
head = "Application controllers"
[admin:components:controllers:tree]
head = "Available controllers:"
[admin:components:controllers:details]
head = "Link details"
[admin:components:controllers:units]
kb = " KB"
[admin:components:controllers:js]
view = "View"
edit = "Edit"
