# ---------------------------------------------------------------- #
#                     Дерево и контент страниц сайта               #
# ---------------------------------------------------------------- #
[admin:content:tree]
title = "Page structure"
[admin:content:tree:tree]
head = "Site page structure:"
[admin:content:tree:detail]
head = "About this link"

# ---------------------------------------------------------------- #
#                Работа со списком страниц сайта                   #
# ---------------------------------------------------------------- #
[admin:content:page]
title = "Working with site pages"
[admin:content:page:page]
head = "Site pages"
[admin:content:page:search]
placeholder = "Search: page name + enter"
[admin:content:page:tools]
[admin:content:page:tools:clear]
icon = "fa fa-wrench"
[admin:content:page:tools:remove]
head = "Clear change history"
icon = "fa fa-trash"
[admin:content:page:modal]
head   = "Are you sure?"
cancel = "Cancel"
delete = "Delete page"
[admin:content:page:visits]
head = "Views"

# ---------------------------------------------------------------- #
#                      Сообщения эндпоинтов                        #
# ---------------------------------------------------------------- #
[admin:content:head:save:error]
text = "An error occurred"
[admin:content:page:save:fail]
text = "Unable to save page"
