# ---------------------------------------------------------------- #
#                   Редактор и конструктор базы данных             #
# ---------------------------------------------------------------- #
[admin:db:editor]
head = "Connection editor"
[admin:db:editor:banner]
head = "Connection editor"
info = "Manage the database connection"
[admin:db:editor:form]
head = "Connection editor"
name.label = "Name"
name.title = "Connection name"
name.help  = "Enter a connection name (English and Russian letters are accepted)"
info.label = "Description"
info.title = "Description"
info.help  = "A comment describing this connection"
pdo.label  = "PDO"
type     = "Driver"
host     = "Host"
dbname   = "Database name (file path)"
user     = "Login"
password = "Password"
cancel = "Cancel"
save   = "Save changes"
# ---------------------------------------------------------------- #
#                    Управление подключениями к БД                 #
# ---------------------------------------------------------------- #
[admin:db:connects]
head = "Database connections"
[admin:db:connects:banner]
head = "Database connection management"
info = "All connections created here are available anywhere in the application via"
param = "connection name"
[admin:db:connects:form]
type.placeholder = "DSN driver"
host.label = "Host (if the database is on a server)"
host.placeholder = "Host (for RDBMS)"
dbname.label = "Database name (or file name)"
dbname.placeholder = "Database name (or file)"
login = "Login"
password = "Password"
submit = "Create connection"
[admin:db:connects:list]
head = "Created connections"
total = "Total:"
mb = " MB"
online = "connection established"
offline = "no connection"
edit = "Edit"
delete = "Delete connection"
# ---------------------------------------------------------------- #
#                      Таблицы, конструктор, записи                #
# ---------------------------------------------------------------- #
[admin:db:table]
head = "Table"
[admin:db:table:view]
btn.add        = "Add record"
btn.create     = "Add table"
btn.drop       = "Drop table"
btn.delconfirm = "Delete?"
btn.del        = "Delete"
notice         = "Table data has been changed. Reload the page to display it"
modal          = "Table record"
[admin:db:construct]
head       = "Table fields constructor"
addfield   = "Add field"
addkey     = "Add key"
tablename  = "Table name (A-z_)"
save       = "Save"
th.name    = "DB field name"
th.desc    = "Field description"
th.data    = "Stored data kind"
fieldname  = "(only A-z_)"
fieldhead  = "(Title)"
pkey       = "Primary key"
autoinc    = "Autoincrement"
[admin:db:create:connfail]
text = "Connection error: "
[admin:db:recordset:dirmake]
text = "Failed to get write access to filesystem in %s"
[admin:db:recordset:fileerr]
text = "Errors occurred while processing the file!"
[admin:db:recordset:uploadfail]
text = "Failed to upload file <b>%s</b> Files of this size may not be supported. <br>"
[admin:db:recordset:updated]
text = "Record updated successfully. If you need actual data - reload the table"
[admin:db:recordset:added]
text = "Record added successfully. If you need actual data - reload the table"
