# ---------------------------------------------------------------- #
#                          Файловый менеджер                       #
# ---------------------------------------------------------------- #
[admin:filemanager]
head = "File manager"
[admin:filemanager:folders]
head = "Quick links"
list.main.head = "Home"
list.themes.head = "Templates"
list.controllers.head = "Controllers"
list.public.head = "Public"
list.units.head = "Modules"
[admin:filemanager:buttons]
back.title = "Back"
mkdir.title = "Create directory"
mkfile.title = "Create file"
paste.title = "Paste"
upload.head = "Upload file"
[admin:filemanager:tools]
uniq = "Generate name"
direct = "Method: Direct POST"
chunk = "Method: Stream"
[admin:filemanager:info]
head = "Info:"
empty = "Select an item to view its information"
[admin:filemanager:clipboard]
head = "Clipboard:"
[admin:filemanager:file]
copy.title = "Copy"
rename.title = "Rename"
download.title = "Download"
delete.title = "Delete"
[admin:filemanager:info:labels]
created = "Created:"
modified = "Modified:"
size = "Size:"
access = "access:"
full = "full"
limited = "limited"
edit.head = "Edit"
[admin:filemanager:info:units]
list.0 = " B"
list.1 = " KB"
list.2 = " MB"
list.3 = " GB"
list.4 = " TB"
[admin:filemanager:info:notfound]
text = "Item %s not found"
[admin:filemanager:js]
rename = "Rename object. Enter a new name:"
mkdir = "Create directory:"
mkfile = "Enter file name:"
delete = 'Delete object "%s"?'
result = "Method returned result: %s"
copied = "In clipboard"
uplerr = "File upload error"
nostream = "Browser does not support chunked upload"
sending = "Sending file ⌛"
uploaded = "Uploaded"
senderr = "Send error"
[admin:filemanager:mkdir:fail]
text = "Failed to create directories..."
[admin:filemanager:mkfile:fail]
text = "Failed to create file..."
[admin:filemanager:copy:nosrc]
text = "Source item not found"
[admin:filemanager:copy:clipboard]
text = "Clipboard is empty"
[admin:filemanager:copy:out]
text = "Target directory is out of reach"
[admin:filemanager:copy:self]
text = "Cannot copy an item into itself"
[admin:filemanager:copy:fail]
text = "Copy error"
[admin:filemanager:delete:fail]
text = "Delete error: "
[admin:filemanager:rename:badname]
text = "Invalid name"
[admin:filemanager:rename:exists]
text = "An item with this name already exists"
[admin:filemanager:rename:fail]
text = "Rename error"
[admin:filemanager:upload:deny]
text = "Access restriction to the target directory"
