# ---------------------------------------------------------------- #
#                          Блок <head> страницы                    #
# ---------------------------------------------------------------- #
[admin:head:index]
title = "Head management"
[admin:head:save]
head  = "Save"
title = "Save changes"
[admin:head:help]
head = "Head tag content <b> &lt;head&gt; </b>"
text = "The &lt;head&gt; tag is designed to hold service information about the page. It is placed first inside the &lt;html&gt; tag, immediately before &lt;body&gt;. Inside &lt;head&gt; are usually the page title, keywords, description and other service data. External resources, such as styles, are also linked there. The contents of this tag are not displayed on the page directly."
[admin:head:toast]
error = "An error occurred"

