# ---------------------------------------------------------------- #
#                          Страница авторизации                    #
# ---------------------------------------------------------------- #
[admin:login]
head = "Authorization"
[admin:login:form]
login    = "Login"
password = "Password"
submit   = "Sign in"
failed   = "Authorization failed"
