# ---------------------------------------------------------------- #
#                         Управление медиа                         #
# ---------------------------------------------------------------- #
[admin:mediafiles]
head  = "Media"
title = "Mediafiles"
[admin:mediafiles:reload]
head = "Reload"
[admin:mediafiles:upload]
head = "Upload file"
[admin:mediafiles:index]
head = "Reindex"
run  = "Indexing"
[admin:mediafiles:delete]
title   = "Delete file"
confirm = "Are you sure you want to perform this action?"
[admin:mediafiles:format:grid]
head = "Grid"
[admin:mediafiles:format:table]
head = "Table"
[admin:mediafiles:search]
placeholder = "Search: file name + enter"
[admin:mediafiles:stat:count]
suffix = "files"
[admin:mediafiles:stat:size]
suffix = "used"
[admin:mediafiles:cols]
list.name.head     = "Name"
list.size.head     = "Size"
list.path.head     = "Path"
list.type.head     = "Type"
list.modified.head = "Modified"

