# ---------------------------------------------------------------- #
#                          Главное меню админки                    #
# ---------------------------------------------------------------- #
[admin:menu:dashboard]
head = "Monitoring"
icon = "fa fa-tachometer"

[admin:menu:content]
head = "Content"
icon = "fa fa-folder-open-o"

[admin:menu:content:mediafiles]
head = "Media files"
[admin:menu:content:page]
head = "Pages"
[admin:menu:content:head]
head = "Headers"
[admin:menu:content:robot]
head = "Robot.txt"
[admin:menu:content:tree]
head = "Sitemap"

[admin:menu:catalogs]
head = "Catalogs"
[admin:menu:catalogs:index]
head = "List"

[admin:menu:constructor]
head = "Constructor"
[admin:menu:constructor:object]
head = "Objects"
[admin:menu:constructor:gallery]
head = "Galleries"
[admin:menu:constructor:form]
head = "Forms"

[admin:menu:communication]
head = "Communication"
[admin:menu:communication:talk]
head = "Talk"
[admin:menu:communication:tg]
head = "Telegram"

[admin:menu:tools]
head = "Tools"
[admin:menu:tools:filemanager]
head = "File manager"
[admin:menu:tools:codeeditor]
head = "Code editor"
[admin:menu:tools:journal]
head = "Journal"

[admin:menu:db]
head = "Databases"
[admin:menu:db:connects]
head = "Connections"

[admin:menu:components]
head = "Components"
[admin:menu:components:controllers]
head = "Controllers"
[admin:menu:components:providers]
head = "Providers"
[admin:menu:components:units]
head = "Models"
[admin:menu:components:packages]
head = "Packages"

[admin:menu:options]
head = "Settings"
[admin:menu:options:users]
head = "Users"
[admin:menu:options:about]
head = "Customization"
[admin:menu:options:env]
head = "ENV files"
[admin:menu:options:install]
head = "Installation"

[admin:menu:manual]
head = "Documentation"
[admin:menu:manual:gitwiki]
head = "GitHub Wiki"

