# ---------------------------------------------------------------- #
#                    Установка, окружение и настройки              #
# ---------------------------------------------------------------- #
[admin:options:env:title]
head = "Environment variables"
[admin:options:about:title]
head = "About the project"
[admin:options:install]
head = "Install objects"
[admin:options:install:installed]
text = "Installed objects: "
[admin:options:env:list]
app  = "Application ENV"
core = "Platform ENV"
# ---------------------------------------------------------------- #
#                            О проекте                             #
# ---------------------------------------------------------------- #
[admin:options:about:poster]
head = "Graphic material"
button = "Upload new poster"
geo = "Geo location"
country = "Russia"
[admin:options:about:info]
head = "Description"
name = "Company name"
greet = "Greeting"
desc.label = "Description"
desc.placeholder = "Description and reference information"
save = "Save"
[admin:options:about:js]
problem = "Problems occurred"
neterr = "A client-server error occurred!"
# ---------------------------------------------------------------- #
#                          Пользователи                            #
# ---------------------------------------------------------------- #
[admin:options:users]
head = "Users"
[admin:options:users:menu]
list.1.head = "Add user"
list.2.head = "Manage roles"
[admin:options:users:card]
disable = "Disabled"
active  = "Active"
desc    = "Description:"
[admin:options:users:edit:profile]
head = "User profile"
avatar = "Load new avatar&hellip;"
desc.head = "Description"
desc.placeholder = "Enter a description for this user"
[admin:options:users:edit:account]
head = "Account"
newlogin.help = "Enter a login for the new user"
newlogin.label  = "Login"
newpassword = "Password"
password.label  = "Password:"
password.new = "New password"
more  = "Additional information:"
name  = "Name"
email = "Email"
group.head    = "Group"
group.default = "Default"
group.admin   = "Admins"
lang.head   = "Interface language"
lang.system = "System"
disable = "Disable profile"
delete  = "Delete"
save    = "Save"
create  = "Create profile"
[admin:options:users:edit:modal]
head = "Deleting profile"
warn = "Deleting a user profile revokes all administration access privileges. The user is deleted permanently."
alt  = "If the account is temporarily not needed, it is better to disable it."
close = "Close"
delete = "Delete account"
srclose = "Close"
[admin:options:users:edit:deny]
head = "List of denied methods"
roles = "Roles"
savepreset = "Save current"
[admin:options:users:edit:js]
presetname = "Enter preset name"
done = "Done"
preseterr = "An error occurred while applying the preset"
[admin:options:users:lock]
head = "Screen locked"
[admin:options:users:lock:block]
word.first = "LOCKED"
word.second = "SCREEN"
info = "This user has locked access to the panel in this browser session. The lock will be automatically released when the session expires."
unlock = "Unlock"
[admin:options:users:deny]
head = "Access restricted"
[admin:options:users:deny:error]
head = "500"
text = "Access to this page is restricted by the rights policy"
[admin:options:users:save:toobig]
text = "File size exceeds 32 megabytes"
[admin:options:users:save:uploaderr]
text = "File upload error"
[admin:options:users:msg:ok]
text = "Success"
[admin:options:users:msg:fail]
text = "Error"
[admin:options:users:presets]
head = "Role management"
[admin:options:users:presets:roles]
head = "Roles:"
rename = "Rename"
[admin:options:users:presets:access]
head = "Method access"
savenew = "Save as new role"
save = "Save"
[admin:options:users:presets:js]
presetname = "Enter preset name"
delconfirm = "Delete role %s?"
done = "Done"
preseterr = "An error occurred while applying the preset"
