# ---------------------------------------------------------------- #
#                         Редактор страницы                        #
# ---------------------------------------------------------------- #
[admin:page:edit]
title = "Page editor"
[admin:page:edit:form]
searche.head = "Interactive search"
edit.head    = "Page settings"
edit.info    = "Save the page as soon as you make the necessary changes. If you need a copy - enter a new address"
edit.url.head = "Page URL"
edit.url.info = "If you need a copy of this page - just enter a new url address. A new page will be created at the specified address and this version will be saved"
edit.html.head = "HTML file"
edit.html.info = "Select an html file to create the page. All available template tags can be seen after the first save"
edit.public.head = "Publication"
edit.index.head  = "Home page"
edit.sitemap.head = "Add to sitemap"
edit.delay.head = "Publish at:"
edit.openpage.head = "Open page"
edit.openpage.title = "Open this page in a new tab"
edit.button.apply.head = "Apply"
edit.button.apply.title = "Save and stay on this page"
edit.button.applyreturn.head = "Save"
edit.button.applyreturn.title = "Save and return to list"
edit.button.preview.head = "Preview"
edit.button.preview.title = "View current changes without saving"
edit.button.timeline.head = "History"
edit.button.timeline.title = "History of changes for this page"
[admin:page:edit:tags]
array.menu = "Menu and navigation"
array.nav = "Navigation and menu =))"
array.section = "Section"
array.gallery = "Image galleries"
array.slider = "Sliders and carousels"
array.catalog = "Catalog (products, goods)"
string.title = "Page title"
string.head = "Page title"
html.body = "Page body"
html.copyright = "Copyright"
[admin:page:edit:objects]
collection = "Object collections"
noncollection = "Object without collection"
other = "Other sources"
text = "Specify value:"
source = "Run php script"
[admin:page:edit:nohtmlmessage]
text = "Template file missing: <b>%s</b>"
type = "warning"
[admin:page:edit:file:choose]
head = "Select file"
icon = "fa-file-code-o"
[admin:page:edit:file:open]
head = "Open code"
icon = "fa-slack"
[admin:page:edit:help]
head = "Help"
text = "Select the file that will be used as the frame for filling the content. Files suitable for use as templates are highlighted in green. You can use template files from different themes. Please note that different template files may provide different functionality."
[admin:page:edit:openas]
head = "Edit as:"
[admin:page:edit:openas:gallery]
head = "Gallery"
[admin:page:edit:openas:objectini]
head = "In text form"
[admin:page:edit:openas:object]
head = "Abstract object"
[admin:page:edit:single]
head = "String variables"

# ---------------------------------------------------------------- #
#                    История изменений страницы                    #
# ---------------------------------------------------------------- #
[admin:page:timeline]
title = "Page history: "
[admin:page:timeline:display]
head = "Display settings:"
[admin:page:timeline:changes:insert]
head = "Added:"
[admin:page:timeline:changes:update]
head = "Updated:"
[admin:page:timeline:changes:delete]
head = "Deleted:"
[admin:page:timeline:view]
head = "View this version"
style = "default"
target = "_blank"
[admin:page:timeline:rollback]
head = "Restore this version"
style = "primary"
[admin:page:timeline:light]
head = "Light version"
[admin:page:timeline:standard]
head = "Standard version"
[admin:page:timeline:orientation]
head = "Change orientation"

