# ---------------------------------------------------------------- #
#          Контекстное меню  профиля пользователя                  #
# ---------------------------------------------------------------- #
[admin:profile:profile]
head = "Profile"
[admin:profile:history]
head = "History"
[admin:profile:lock]
head = "Lock"
[admin:profile:logout]
head = "Logout"

