#!/usr/bin/php
<?php
/*
 * console.php
 *
 * Copyright 2025 vladimir <vladimir@MacBookAir>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 *
 */

error_reporting(E_ALL & ~E_NOTICE);

# ---------------------------------------------------------------- #
#               Инициализация переменных окружения                 #
# ---------------------------------------------------------------- #
$_ENV = array_merge(parse_ini_file(".env", true), $_ENV);


# ---------------------------------------------------------------- #
#             Объявление автозагрузки (стандарт PSR4)              #
# ---------------------------------------------------------------- #
//Подключаем файл с окружением ядра
include_once $_ENV['core']['path']."core.php";


# ---------------------------------------------------------------- #
#                     Инициализация приложения                     #
# ---------------------------------------------------------------- #
//Создаем приложение (указав диретории размещения расширений ядра, фасадов, моделей и библиотек)
$APP = new APP($_ENV['core']['path'], $_ENV['facades'], $_ENV['vendor']['path']);
//Загрузим переменные окружения
$APP->config->loadENV(['.env', 'app/.env']);


$command  = isset($argv[1]) ? $argv[1] : 'help';
$method   = isset($argv[2]) ? $argv[2] : '';

try
{
	$result = method_exists($APP->console->$command, $method)
			? $APP->console->$command->$method(array_slice((array)$argv, 3))
			: $APP->console->$command(array_slice((array)$argv, 2));
}
catch (Throwable $e)
{
echo "
　　　　　　／＞　 フ
　　　　　 /　_　 _|
　 　　　／`ミ _x 彡
　　 　 /　　　 　/
　　　 /　 ヽ　　 ﾉ
　／￣|　　 |　| |
 | (￣ヽ_＿_ヽ_)_)
　＼二つ
";
	$APP->console->print( $e->getMessage(), E_ERROR );
	exit((!$errorCode = $e->getCode()) ? 12 : $errorCode);
}
