[view]
profile.head          = 'Профиль пользователя'
profile.avatar        = 'Загрузить новый аватар&hellip;'
profile.desc.head     = 'Описание'
profile.desc.placeholder = 'Введите описание для этого пользователя'
profile.l10n          = 'admin:options:users:edit:profile'

account.head            = 'Учетная запись'
account.newlogin.help   = 'Введите логин нового пользователя'
account.newlogin.label  = 'Логин'
account.newpassword     = 'Пароль'
account.password.label  = 'Пароль:'
account.password.new    = 'Новый пароль'
account.more            = 'Дополнительная информация:'
account.name            = 'Имя'
account.email           = 'Email'
account.group.head      = 'Группа'
account.group.default   = 'Базовая'
account.group.admin     = 'Администраторы'
account.disable         = 'Отключить профиль'
account.delete          = 'Удалить'
account.save            = 'Сохранить'
account.create          = 'Создать профиль'
account.l10n            = 'admin:options:users:edit:account'

modal.head    = 'Удаление профиля'
modal.warn    = 'Удаление профиля пользователя отменит все привелегии доступа к администрированию. Пользователь удаляется безвозвратно.'
modal.alt     = 'Если учетная запись временно не нужна, её целесообразно отключить.'
modal.close   = 'Закрыть'
modal.delete  = 'Удалить учетную запись'
modal.srclose = 'Закрыть'
modal.l10n    = 'admin:options:users:edit:modal'

deny.head       = 'Список запрещенных методов'
deny.roles      = 'Роли'
deny.savepreset = 'Сохранить текущий'
deny.l10n       = 'admin:options:users:edit:deny'

;JS-строки шаблона — data-* на форме #form-edit
js.presetname = 'Введите название пресета'
js.done       = 'Готово'
js.preseterr  = 'Возникла ошибка применения пресета'
js.l10n       = 'admin:options:users:edit:js'
