[view]
title.head = 'Блокировка экрана'
title.l10n = 'admin:options:users:lock'

;Двухцветный баннер сверху: первое слово подсвечено
lock.word.first  = 'ЭКРАН'
lock.word.second = 'ЗАБЛОКИРОВАН'
lock.info   = 'Данный пользователь заблокировал доступ к панели в этой сессии браузера. Блокировка будет автоматически снята по истечению времени сессии.'
lock.unlock = 'Разблокировать'
lock.l10n   = 'admin:options:users:lock:block'
