[view]
title.head = 'Авторизация'
title.l10n = 'admin:login'

;head и action наполняются контроллером
form.authorization.head    = ''
form.authorization.action  = ''
form.authorization.login   = 'Логин'
form.authorization.password = 'Пароль'
form.authorization.submit  = 'Войти'
form.authorization.failed  = 'Не удалось авторизоваться'
form.authorization.l10n    = 'admin:login:form'

;ссылка на постер наполняется контроллером
poster.link = ''
