;Статическая структура страницы admin/content/page
[view]
title = 'Работа со страницами сайта'
l10n  = 'admin:content:page'

page.head = 'Страницы сайта'
page.l10n = 'admin:content:page:page'

search.placeholder = 'Поиск страницы + enter'
search.l10n = 'admin:content:page:search'

tools.l10n = 'admin:content:page:tools'
tools.list.clear.icon = 'fa fa-wrench'
tools.list.clear.button.list.remove.head = 'Очистить историю изменений'
tools.list.clear.button.list.remove.icon = 'fa fa-trash'
tools.list.clear.button.list.remove.link = 'admin/content/page/timeline/remove'
tools.list.clear.button.list.remove.l10n = 'admin:content:page:tools:remove'
tools.list.clear.l10n = 'admin:content:page:tools:clear'

modal.head   = 'Уверены?'
modal.cancel = 'Отмена'
modal.delete = 'Удалить страницу'
modal.l10n   = 'admin:content:page:modal'

visits.head = 'Просмотров'
visits.l10n = 'admin:content:page:visits'
