#=======================================================================
#				Объекты устанавливаемого приложения
#=======================================================================


[catalog]



[gallery]



[article]



[menu]







#=======================================================================
#				Объекты, поставляемые для панели
#=======================================================================


[admin.mainmenu.list]
dashboard.head = "Мониторинг"
dashboard.link = "admin/dashboard"
dashboard.icon = "fa fa-th-large"
content.head = "Содержимое"
content.link = "admin/content"
content.icon = "fa fa-file-text-o"
content.list.mediafiles.head = "Медиафайлы"
content.list.mediafiles.link = "admin/content/mediafiles/"
content.list.page.head = "Страницы"
content.list.page.link = "admin/content/page"
content.list.head.head = "Заголовки"
content.list.head.link = "admin/content/head"
content.list.robot.head = "Robot.txt"
content.list.robot.link = "admin/tools/codeeditor?file=app/controllers/robot.txt.php"
content.list.tree.head = "Карта"
content.list.tree.link = "admin/content/tree"
catalogs.head = "Справочники"
catalogs.link = "admin/catalogs"
catalogs.icon = "fa fa-columns"
catalogs.list.index.head = "Список"
catalogs.list.index.link = "admin/catalogs/index"
constructor.head = "Конструктор"
constructor.link = "admin/constructor"
constructor.icon = "fa fa-paint-brush"
constructor.list.object.head = "Объекты"
constructor.list.object.link = "admin/constructor/object"
constructor.list.gallery.head = "Галереи"
constructor.list.gallery.link = "admin/constructor/gallery"
constructor.list.form.head = "Формы"
constructor.list.form.link = "admin/constructor/form"
communication.head = "Коммуникация"
communication.link = "admin/communication"
communication.icon = "fa fa-comments-o"
communication.list.talk.head = "Обсуждение"
communication.list.talk.link = "admin/communication/talk"
communication.list.talk.icon = "fa fa-comments-o"
communication.list.tg.head = "Телеграм"
communication.list.tg.link = "admin/communication/tg"
tools.head = "Утилиты"
tools.link = "admin/tools"
tools.icon = "fa fa-legal"
tools.list.filemanager.head = "Файловый менеджер"
tools.list.filemanager.link = "admin/tools/filemanager"
tools.list.codeeditor.head = "Редактор кода"
tools.list.codeeditor.link = "admin/tools/codeeditor"
tools.list.journal.head = "Журнал"
tools.list.journal.link = "admin/tools/journal"
db.head = "Базы данных"
db.link = "admin/db"
db.icon = "fa fa-database"
db.list.connects.head = "Соединения"
db.list.connects.link = "admin/db/connects"
components.head = "Компоненты"
components.link = "admin/components"
components.icon = "fa fa-cogs"
components.list.controllers.head = "Контроллеры"
components.list.controllers.link = "admin/components/controllers"
components.list.providers.head = "Провайдеры"
components.list.providers.link = "admin/components/providers"
components.list.units.head = "Модели"
components.list.units.link = "admin/components/units"
components.list.packages.head = "Пакеты"
components.list.packages.link = "admin/components/packages"
options.head = "Параметры"
options.link = "admin/options"
options.icon = "fa fa-sliders"
options.list.users.head = "Пользователи"
options.list.users.link = "admin/options/users"
options.list.about.head = "Кастомизация"
options.list.about.link = "admin/options/about"
options.list.env.head = "Файлы ENV"
options.list.env.link = "admin/options/env"
options.list.install.head = "Инсталяция"
options.list.install.link = "admin/options/install/"
manual.head = "Документация"
manual.link = "admin/manual"
manual.icon = "fa fa-graduation-cap"
manual.list.gitwiki.head = "Wiki на GitHub"
manual.list.gitwiki.link = "https://github.com/Qlaster/Quark/wiki"
manual.list.gitwiki.target = "_blank"


[admin.profilemenu.list]
profile.head = "Профиль"
profile.link = "admin/options/users/im"
profile.icon = "fa fa-tasks"
history.head = "История"
history.link = "admin/tools/journal"
history.icon = "fa fa-list"
lock.head = "Заблокировать"
lock.link = "admin/options/users/lock"
lock.icon = "fa fa-lock"
logout.head = "Выход"
logout.link = "admin/options/users/logout"
logout.icon = "fa fa-sign-out"



[admin.mimeicon.list]
0.mime = "text/plain"
0.icon = "fa fa-file-text-o"
0.type = ""
0.format = "text"
0.ext = "txt"
1.mime = "text/html"
1.icon = "fa fa-code"
1.type = ""
1.format = "code"
1.ext = "html"
2.mime = "text/css"
2.icon = "fa fa-css3"
2.type = ""
2.format = "code"
2.ext = "css"
3.mime = "application/javascript"
3.icon = "fa fa-code"
3.type = ""
3.format = "code"
3.ext = "js"
4.mime = "application/json"
4.icon = "fa fa-codepen"
4.type = ""
4.format = "json"
4.ext = "json"
5.mime = "application/xml"
5.icon = "fa fa-codepen"
5.type = ""
5.format = "xml"
5.ext = "xml"
6.mime = "application/x-shockwave-flash"
6.icon = "fa fa-flash"
6.type = ""
6.format = "flash"
6.ext = "swf"
7.mime = "video/x-flv"
7.icon = "fa-youtube-play"
7.type = ""
7.format = "video"
7.ext = "flv"
8.mime = "image/png"
8.icon = "fa fa-picture-o"
8.type = ""
8.format = "image"
8.ext = "png"
9.mime = "image/jpeg"
9.icon = "fa fa-picture-o"
9.type = ""
9.format = "image"
9.ext = "jpeg"
10.mime = "image/gif"
10.icon = "fa fa-picture-o"
10.type = ""
10.format = "image"
10.ext = "gif"
11.mime = "image/bmp"
11.icon = "fa fa-picture-o"
11.type = ""
11.format = "image"
11.ext = "bmp"
12.mime = "image/vnd.microsoft.icon"
12.icon = "fa fa-picture-o"
12.type = ""
12.format = "image"
12.ext = "ico"
13.mime = "image/tiff"
13.icon = "fa fa-picture-o"
13.type = ""
13.format = "image"
13.ext = "tiff"
14.mime = "image/svg+xml"
14.icon = "fa fa-picture-o"
14.type = ""
14.format = "image"
14.ext = "svg"
15.mime = "application/zip"
15.icon = "fa fa-file-zip-o"
15.type = ""
15.format = "zip"
15.ext = "zip"
16.mime = "application/x-rar-compressed"
16.icon = "fa fa-file-zip-o"
16.type = ""
16.format = "zip"
16.ext = "rar"
17.mime = "application/x-msdownload"
17.icon = "fa fa-windows"
17.type = ""
17.format = "app"
17.ext = "exe"
18.mime = "application/vnd.ms-cab-compressed"
18.icon = "fa fa-file-zip-o"
18.type = ""
18.format = "zip"
18.ext = "cab"
19.mime = "audio/mpeg"
19.icon = "fa fa-music"
19.type = ""
19.format = "audio"
19.ext = "mp3"
20.mime = "video/quicktime"
20.icon = "fa fa-youtube-play"
20.type = ""
20.format = "video"
20.ext = "mov"
21.mime = "application/pdf"
21.icon = "fa fa-file-pdf-o"
21.type = ""
21.format = "doc"
21.ext = "pdf"
22.mime = "image/vnd.adobe.photoshop"
22.icon = ""
22.type = ""
22.format = "vnd.adobe.photoshop"
22.ext = "psd"
23.mime = "application/postscript"
23.icon = "fa fa-code"
23.type = ""
23.format = "code"
23.ext = "ps"
24.mime = "application/msword"
24.icon = "fa fa-file-word-o"
24.type = ""
24.format = "doc"
24.ext = "doc"
25.mime = "application/rtf"
25.icon = "fa fa fa-file-text-o"
25.type = ""
25.format = "doc"
25.ext = "rtf"
26.mime = "application/vnd.ms-excel"
26.icon = "fa fa-file-excel-o"
26.type = ""
26.format = "doc"
26.ext = "xls"
27.mime = "application/vnd.ms-powerpoint"
27.icon = "fa fa-file-powerpoint-o"
27.type = ""
27.format = "doc"
27.ext = "ppt"
28.mime = "application/vnd.oasis.opendocument.text"
28.icon = "fa fa-file-word-o"
28.type = ""
28.format = "doc"
28.ext = "odt"
29.mime = "application/vnd.oasis.opendocument.spreadsheet"
29.icon = "fa fa-file-word-o"
29.type = ""
29.format = "doc"
29.ext = "ods"
30.mime = "application/pkcs10"
30.icon = "fa fa-cc"
30.type = ""
30.format = "key"
30.ext = "csr"
31.mime = "text/x-php"
31.icon = "fa fa-code"
31.type = ""
31.format = "code"
31.ext = "php"
32.mime = "application/x-iwork-keynote-sffkey"
32.icon = "fa fa-cc"
32.type = ""
32.format = "key"
32.ext = "key"
33.mime = "application/vnd.debian.binary-package"
33.icon = "fa fa-linux"
33.type = ""
33.format = "app"
33.ext = "deb"
34.mime = "application/x-ms-dos-executable"
34.icon = "fa fa-windows"
34.type = ""
34.format = "app"
34.ext = "exe"
35.mime = "application/x-java-jnlp-file"
35.icon = "fa fa-code"
35.type = ""
35.format = "code"
35.ext = "jnlp"
36.mime = "application/x-shellscript"
36.icon = "fa fa-slack"
36.type = ""
36.format = "code"
36.ext = "sh"
37.mime = "application/x-extension-sqlite"
37.icon = "fa fa-database"
37.type = ""
37.format = "database"
37.ext = "sqlite"
38.mime = "application/vnd.rars"
38.icon = "fa fa-file-zip-o"
38.type = ""
38.format = "zip"
38.ext = "rar"
39.mime = "video/mp4"
39.icon = "fa fa-youtube-play"
39.type = ""
39.format = "video"
39.ext = "mp4"
40.mime = "application/octet-stream"
40.icon = "fa fa-music"
40.type = ""
40.format = "audio"
40.ext = "mp3"
41.mime = "application/x-dosexec"
41.icon = "fa fa-windows"
41.type = ""
41.format = "app"
41.ext = "exe"


