[view]
range = 15
limit = 50


[upload]
#Диреткория загрузки файлов
folder = public/catalogs/
#переименовывать загружаемые файлы в уникальные имена
renaming = false


[patterns]
text.head = "Текст"
int.head = "Целое число"
real.head = "Целое или дробное число"
html.head = "HTML код"
link.head = "Ссылка"
image.head = "Ссылка на картинку"
video.head = "Ссылка на видео"
audio.head = "Ссылка на аудио"
blob.head = "Бинарные данные"
check.head = "Переключатель"
date.head = "Дата"
datetime.head = "Дата и время"
checkdate.head = "Флажок с датой"
input.head = "Нативный input"
relation.head = "Связь с другим каталогом"

[list]
#Условия подключения
account.db = "account"
account.table = "account"
account.icon = "fa-user"
account.head = "Аккаунты пользователей"
account.info = "Список учетных записей базы аккаунтов"
account.help = "При внесении новых пользователей обеспечте уникальность их адресов электронной почты"
#Интервал в секундах, для проверки обновлений, когда каталог открыт
account.refresh = 10

#События отбора
account.events.view.column =
account.events.view.groupby =
account.events.view.orderby =
account.events.view.where =
#Описание полей
account.field.id.type = "id"
account.field.login.alias  = "Логин"
account.field.login.type  = "text"
account.field.name.alias  = "Имя"
account.field.name.type  = "text"
account.field.head.alias  = "Заголовок"
account.field.head.type  = "text"
account.field.image.alias  = "Логотип"
account.field.image.type  = "image"
#account.field.access.alias  = "Права"
#account.field.access.type  = "select"
#account.field.access.source  = access.name
account.field.info.alias  = "Описание"
account.field.info.type  = "html"

account.field.online.alias  = "Онлайн"
account.field.online.type  = "integer"
account.field.online.type  = "check"

account.field.disable.alias  = "Блокировка"
account.field.disable.type  = "check"
account.field.docs.alias  = "Файлы"
account.field.docs.type  = "files"
account.field.audio.alias = Ролик
account.field.audio.type = audio
#Классический input с возможностью передать любой нативный тип
account.field.color.alias = Цвет
account.field.color.type = input
account.field.color.input = color

#Связь на внешний каталог. Примеры:
#1. Текущая БД (обратная совместимость)
#articles.field.category_id.source = "categories::name"
#2. Явное указание подключения
#articles.field.category_id.source = "products_db::categories::name"
#3. Через другой каталог
#articles.field.category_id.source = "products::categories::name"

; Таблица в БД текущего каталога
#articles.field.category_id.alias  = "Категория"
#articles.field.category_id.type   = "relation"
#articles.field.category_id.source = "categories::name"

; Таблица в БД другого каталога (или явное имя DB-соединения)
#articles.field.author_id.alias  = "Автор"
#articles.field.author_id.type   = "relation"
#articles.field.author_id.source = "users::accounts::login"
#Тут мы игнорируем relation во view, но покажем его при редактировании
#articles.field.author_id.ignore = 1


account.field.review.alias  = "Категория сообщения"
account.field.review.type   = "relation"
account.field.review.source = "review::posts::name"
#Нужно ли игнорировать при выводе view
account.field.review.ignore = 1



review.db = "review"
review.table = "posts"
review.head = "Обратная связь"
review.info = "База данных для сбора обратной связи"
review.icon = fa-comments




