[db]
name = "review"

[table]
blogs    = "talk_blogs"
posts    = "talk_posts"
messages = "talk_messages"


[upload]
; Корневая директория для файлов постов
; Итоговый путь: {folder}/{blogname}/{postname}/
folder = public/talk/
