;Статическая структура страницы admin/content/head
[view]
title = 'Управление заголовками страниц'
l10n  = 'admin:head:index'

save.head  = 'Сохранить'
save.title = 'Сохранить изменения'
save.icon  = 'fa-check-square-o'
save.l10n  = 'admin:head:save'

help.head = 'Содержимое заголовка <b> &lt;head&gt; </b>'
help.text = 'Тег &lt;head&gt; предназначен для хранения служебной информации о странице. Он располагается первым в теге &lt;html&gt;, сразу перед &lt;body&gt;. Внутри &lt;head&gt; обычно содержится заголовок, ключевые слова, описание страницы и другие служебные данные. Также внутри него подключаются внешние ресурсы, например, стили. Содержимое этого тега не отображается на странице напрямую.'
help.l10n = 'admin:head:help'

toast.l10n     = 'admin:head:toast'
toast.error    = 'Возникла ошибка'
