[view]
;Шаблон dbmanager/db_construct.html общий с db/index
construct.head       = 'Конструктор полей таблицы'
construct.addfield   = 'Добавить поле'
construct.addkey     = 'Добавить ключ'
construct.tablename  = 'Название таблицы (A-z_)'
construct.save       = 'Сохранить'
construct.th.name    = 'Название поля db'
construct.th.desc    = 'Описание поля'
construct.th.data    = 'Вид хранимых данных'
construct.fieldname  = '(только A-z_)'
construct.fieldhead  = '(Заголовок)'
construct.pkey       = 'Первичный ключ'
construct.autoinc    = 'Автоинкремент'
construct.l10n       = 'admin:db:construct'
