[view]
table.data.head = 'Таблица'
table.data.l10n = 'admin:db:table'

;Подписи кнопок и модалка в dbmanager/db_table.html
panel.btn.add        = 'Добавить запись'
panel.btn.create     = 'Добавить таблицу'
panel.btn.drop       = 'Удалить таблицу'
panel.btn.delconfirm = 'Удалить?'
panel.btn.del        = 'Удалить'
panel.notice         = 'Данные в таблице были изменены. Для отображения перезагрузите страницу'
panel.modal          = 'Запись в таблице'
panel.l10n           = 'admin:db:table:view'
