;Статическая структура страницы admin/content/tree
[view]
title = 'Структура страниц'
l10n  = 'admin:content:tree'

tree.head   = 'Структура страниц сайта:'
tree.l10n   = 'admin:content:tree:tree'

tree.detail.head = 'Подробнее о ссылке'
tree.detail.l10n = 'admin:content:tree:detail'
