[view]
messages.installed.text = 'Установленные объекты: '
messages.installed.l10n = 'admin:options:install:installed'

;Общее сообщение с codeeditor/save
messages.savefail.text = 'Не удалось сохранить файл'
messages.savefail.l10n = 'admin:codeeditor:savefail'
