[view]
labels.created  = 'Создан:'
labels.modified = 'Изменен:'
labels.size     = 'Размер:'
labels.access   = 'доступ:'
labels.full     = 'полный'
labels.limited  = 'ограниченный'
labels.edit.head = 'Редактировать'
labels.l10n = 'admin:filemanager:info:labels'

;Суффиксы размера — массив, индекс выбирается по порядку величины
units.list.0 = ' Б'
units.list.1 = ' Кб'
units.list.2 = ' Мб'
units.list.3 = ' Гб'
units.list.4 = ' Тб'
units.l10n = 'admin:filemanager:info:units'

messages.notfound.text = 'Элемент %s не найден'
messages.notfound.l10n = 'admin:filemanager:info:notfound'
